stages:
  - build
  - test
  - deploy

variables:
  TEST_ENV: "dev"
  DEPLOY_ENV: "production"

build:
  stage: build
  script:
    - echo "Building the app..."
    - npm install
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying to $DEPLOY_ENV..."
    - scp -r ./build user@server:/var/www/html
  only:
    - master
